export const projectDetailsData = [
  {
    id: 1,
    title: "Agreement No/Date",
    name: "agreementNoDate",
    placeHolder: "Enter Agreement No/Date",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 2,
    title: "Project Name",
    name: "projectName",
    placeHolder: "Enter Project Name",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 3,
    title: "District",
    name: "district",
    placeHolder: "Enter District",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 4,
    title: "No of Villages",
    name: "noOfVillages",
    placeHolder: "Enter Number of Villages",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 5,
    title: "Source",
    name: "source",
    placeHolder: "Enter Source",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 6,
    title: "Capacity of Water Treatment Plant (CWTP)",
    name: "capacityCWTP",
    placeHolder: "Enter CWTP Capacity",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 7,
    title: "Project Population",
    name: "projectPopulation",
    placeHolder: "Enter Project Population",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 8,
    title: "No of Household",
    name: "noOfHousehold",
    placeHolder: "Enter Number of Households",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 9,
    title: "Project Cost",
    name: "projectCost",
    placeHolder: "Enter Project Cost",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 10,
    title: "Project Cost after Up to Date Variation",
    name: "projectCostVariation",
    placeHolder: "Enter Cost after Variation",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 11,
    title: "Funding Agency",
    name: "fundingAgency",
    placeHolder: "Enter Funding Agency",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 12,
    title: "Project Duration",
    name: "projectDuration",
    placeHolder: "Enter Project Duration",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 13,
    title: "Project Start Date",
    name: "projectStartDate",
    placeHolder: "Select Project Start Date",
    required: true,
    type: "input",
    fieldType: "date",
    size: 6,
  },
  {
    id: 14,
    title: "Project Completion Date",
    name: "projectCompletionDate",
    placeHolder: "Select Project Completion Date",
    required: true,
    type: "input",
    fieldType: "date",
    size: 6,
  },
  {
    id: 15,
    title: "Expected Date of Completion",
    name: "expectedCompletionDate",
    placeHolder: "Select Expected Completion Date",
    required: true,
    type: "input",
    fieldType: "date",
    size: 6,
  },
  {
    id: 16,
    title: "Name of Agency",
    name: "agencyName",
    placeHolder: "Enter Name of Agency",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 17,
    title: "Name of Manager",
    name: "managerName",
    placeHolder: "Enter Manager Name",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 18,
    title: "Contact No of Manager",
    name: "managerContact",
    placeHolder: "Enter Manager Contact No",
    required: true,
    type: "input",
    fieldType: "text",
    size: 6,
  },
  {
    id: 19,
    title: "Financial Progress (%)",
    name: "financialProgress",
    placeHolder: "Enter Financial Progress",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 20,
    title: "Physical Progress (%)",
    name: "physicalProgress",
    placeHolder: "Enter Physical Progress",
    required: true,
    type: "input",
    fieldType: "number",
    size: 6,
  },
  {
    id: 21,
    title: "Project Status",
    name: "projectStatus",
    placeHolder: "Enter Project Status",
    required: true,
    type: "select",
    size: 6,
    options: ["In Progress", "Completed", "On Hold", "Cancelled"],
  },
  {
    id: 22,
    title: "Water Supply Start Date",
    name: "waterSupplyStartDate",
    placeHolder: "Select Water Supply Start Date",
    required: false,
    type: "input",
    fieldType: "date",
    size: 6,
  },
];

export const projectHeaders = [
  {
    id: 1,
    label: "ID",
    valueAccessor: "id",
    name: "id",
  },
  {
    id: 2,
    label: "Agreement No/Date",
    valueAccessor: "agreementNoDate",
    name: "agreementNoDate",
    placeHolder: "Enter Agreement No/Date",
    type: "input",
    size: 6,
  },
  {
    id: 3,
    label: "Project Name",
    valueAccessor: "projectName",
    name: "projectName",
    placeHolder: "Enter Project Name",
    type: "input",
    size: 6,
  },
  {
    id: 4,
    label: "District",
    valueAccessor: "district",
    name: "district",
    placeHolder: "Enter District",
    type: "input",
    size: 6,
  },
  {
    id: 5,
    label: "No. of Villages",
    valueAccessor: "noOfVillages",
    name: "noOfVillages",
    placeHolder: "Enter Number of Villages",
    type: "input",
    size: 6,
  },
  {
    id: 6,
    label: "Source",
    valueAccessor: "source",
    name: "source",
    placeHolder: "Enter Source",
    type: "input",
    size: 6,
  },
  {
    id: 7,
    label: "Capacity of Water Treatment Plant",
    valueAccessor: "capacityOfWaterTreatmentPlant",
    name: "capacityOfWaterTreatmentPlant",
    placeHolder: "Enter Capacity",
    type: "input",
    size: 6,
  },
  {
    id: 8,
    label: "Project Population",
    valueAccessor: "projectPopulation",
    name: "projectPopulation",
    placeHolder: "Enter Project Population",
    type: "input",
    size: 6,
  },
  {
    id: 9,
    label: "No. of Households",
    valueAccessor: "noOfHousehold",
    name: "noOfHousehold",
    placeHolder: "Enter No. of Households",
    type: "input",
    size: 6,
  },
  {
    id: 10,
    label: "Project Cost",
    valueAccessor: "projectCost",
    name: "projectCost",
    placeHolder: "Enter Project Cost",
    type: "input",
    size: 6,
  },
  {
    id: 11,
    label: "Project Cost After Variation",
    valueAccessor: "projectCostAfterVariation",
    name: "projectCostAfterVariation",
    placeHolder: "Enter Cost After Variation",
    type: "input",
    size: 6,
  },
  {
    id: 12,
    label: "Funding Agency",
    valueAccessor: "fundingAgency",
    name: "fundingAgency",
    placeHolder: "Enter Funding Agency",
    type: "input",
    size: 6,
  },
  {
    id: 13,
    label: "Project Duration (Days)",
    valueAccessor: "projectDuration",
    name: "projectDuration",
    placeHolder: "Enter Project Duration",
    type: "input",
    size: 6,
  },
  {
    id: 14,
    label: "Project Start Date",
    valueAccessor: "projectStartDate",
    name: "projectStartDate",
    placeHolder: "Enter Start Date",
    type: "date",
    size: 6,
  },
  {
    id: 15,
    label: "Project Completion Date",
    valueAccessor: "projectCompletionDate",
    name: "projectCompletionDate",
    placeHolder: "Enter Completion Date",
    type: "date",
    size: 6,
  },
  {
    id: 16,
    label: "Expected Completion Date",
    valueAccessor: "expectedCompletionDate",
    name: "expectedCompletionDate",
    placeHolder: "Enter Expected Completion Date",
    type: "date",
    size: 6,
  },
  {
    id: 17,
    label: "Agency Name",
    valueAccessor: "agencyName",
    name: "agencyName",
    placeHolder: "Enter Agency Name",
    type: "input",
    size: 6,
  },
  {
    id: 18,
    label: "Manager Name",
    valueAccessor: "managerName",
    name: "managerName",
    placeHolder: "Enter Manager Name",
    type: "input",
    size: 6,
  },
  {
    id: 19,
    label: "Manager Contact",
    valueAccessor: "managerContact",
    name: "managerContact",
    placeHolder: "Enter Manager Contact",
    type: "input",
    size: 6,
  },
  {
    id: 20,
    label: "Financial Progress (%)",
    valueAccessor: "financialProgress",
    name: "financialProgress",
    placeHolder: "Enter Financial Progress",
    type: "input",
    size: 6,
  },
  {
    id: 21,
    label: "Physical Progress (%)",
    valueAccessor: "physicalProgress",
    name: "physicalProgress",
    placeHolder: "Enter Physical Progress",
    type: "input",
    size: 6,
  },
  {
    id: 22,
    label: "Project Status",
    valueAccessor: "projectStatus",
    name: "projectStatus",
    placeHolder: "Enter Project Status",
    type: "input",
    size: 6,
  },
  {
    id: 23,
    label: "Water Supply Start Date",
    valueAccessor: "waterSupplyStartDate",
    name: "waterSupplyStartDate",
    placeHolder: "Enter Water Supply Start Date",
    type: "date",
    size: 6,
  },
  {
    id: 24,
    label: "PIU",
    valueAccessor: "piu",
    name: "piu",
    placeHolder: "Enter PIU",
    type: "input",
    size: 6,
  },
];

